services:
  - type: web
    name: kingo-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        value: postgresql://user:password@localhost/kingo
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: ALLOWED_ORIGINS
        value: https://kingo-portfolio-d0je2u1t8-changrims-projects.vercel.app,http://localhost:3000